version: '3'

services:
  # MongoDB Service
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
    restart: always

  # Node.js Backend Service
  backend:
   image: saigopi1234/snake_backend:latest
    build: ./backend
    container_name: snake-game-backend
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./frontend:/app/public
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
